export default {
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATION_AS_READ: 'MARK_ALL_NOTIFICATION_AS_READ',
    START_NOTIFICATION_FETCH_POST: 'START_NOTIFICATION_FETCH_POST',
    FINISH_NOTIFICATION_FETCH_POST: 'FINISH_NOTIFICATION_FETCH_POST',
    RECEIVED_NOTIFICATION: 'RECEIVED_NOTIFICATION',
    START_LOGIN: 'START_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED'
}